### ISSUE TITLE
关于首行中文

### ISSUE THREAD

**Issue by tumashu** [xuchunyang/emacs-opencc#1]
```
;;; opencc.el --- 中文简繁转换 <-> 中文簡繁轉換  -*- lexical-binding: t; -*-
```
你确定在 package buffer 中可以正确显示中文吗？

**Comment by xuchunyang** [comment]
可以，至少对于 Emacs 25.2 来说。如果你的 Emacs 不可以的话，那也是 Emacs 的问题，跟 emacs-opencc 没什么关系。我暂时没有把它改成英文的打算。

同样的问题以前我们讨论过： https://github.com/melpa/melpa/issues/2313 ，Steve Purcell 已经向上游报告过这个问题并且已经修复了。

**Comment by xuchunyang** [comment]
![screen shot 2017-07-13 at 3 01 54 pm](https://user-images.githubusercontent.com/4550353/28154318-3a1a4250-67dc-11e7-95a7-3b85cf70a480.png)

**Comment by tumashu** [comment]
我靠，还是我提的 issue， 能就好
